# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from omr_service.rpc import omr_pb2 as omr__pb2


class OmrServiceStub(object):
    """OMR 服务 — 黄金模板解析、识别、成功率验证、复验
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseGoldenTemplate = channel.unary_unary(
                '/omr.OmrService/ParseGoldenTemplate',
                request_serializer=omr__pb2.GoldenTemplateRequest.SerializeToString,
                response_deserializer=omr__pb2.GoldenTemplateResult.FromString,
                )
        self.RecognizeByTemplate = channel.unary_unary(
                '/omr.OmrService/RecognizeByTemplate',
                request_serializer=omr__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=omr__pb2.RecognizeResult.FromString,
                )
        self.VerifyRecognitionRate = channel.unary_unary(
                '/omr.OmrService/VerifyRecognitionRate',
                request_serializer=omr__pb2.VerifyRateRequest.SerializeToString,
                response_deserializer=omr__pb2.VerifyRateResult.FromString,
                )
        self.ReverifyPaper = channel.unary_unary(
                '/omr.OmrService/ReverifyPaper',
                request_serializer=omr__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=omr__pb2.RecognizeResult.FromString,
                )


class OmrServiceServicer(object):
    """OMR 服务 — 黄金模板解析、识别、成功率验证、复验
    """

    def ParseGoldenTemplate(self, request, context):
        """解析黄金模板：根据列框配置 + 模板图片，生成气泡网格与标准答案
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeByTemplate(self, request, context):
        """根据黄金模板识别单张答题卡
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyRecognitionRate(self, request, context):
        """验证黄金模板识别成功率（管理端传入已知答案的图片列表）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverifyPaper(self, request, context):
        """单张试卷复验（与 RecognizeByTemplate 等价，语义区分）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OmrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseGoldenTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseGoldenTemplate,
                    request_deserializer=omr__pb2.GoldenTemplateRequest.FromString,
                    response_serializer=omr__pb2.GoldenTemplateResult.SerializeToString,
            ),
            'RecognizeByTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeByTemplate,
                    request_deserializer=omr__pb2.RecognizeRequest.FromString,
                    response_serializer=omr__pb2.RecognizeResult.SerializeToString,
            ),
            'VerifyRecognitionRate': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyRecognitionRate,
                    request_deserializer=omr__pb2.VerifyRateRequest.FromString,
                    response_serializer=omr__pb2.VerifyRateResult.SerializeToString,
            ),
            'ReverifyPaper': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverifyPaper,
                    request_deserializer=omr__pb2.RecognizeRequest.FromString,
                    response_serializer=omr__pb2.RecognizeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omr.OmrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OmrService(object):
    """OMR 服务 — 黄金模板解析、识别、成功率验证、复验
    """

    @staticmethod
    def ParseGoldenTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omr.OmrService/ParseGoldenTemplate',
            omr__pb2.GoldenTemplateRequest.SerializeToString,
            omr__pb2.GoldenTemplateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeByTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omr.OmrService/RecognizeByTemplate',
            omr__pb2.RecognizeRequest.SerializeToString,
            omr__pb2.RecognizeResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyRecognitionRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omr.OmrService/VerifyRecognitionRate',
            omr__pb2.VerifyRateRequest.SerializeToString,
            omr__pb2.VerifyRateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReverifyPaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omr.OmrService/ReverifyPaper',
            omr__pb2.RecognizeRequest.SerializeToString,
            omr__pb2.RecognizeResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
